spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/codefleck
    username: varo
    password: varo
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
